name: Copy images

on:
  push:
    paths:
      - 'images/**'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create target folder
        run: |
          rm -rf images_compressed
          mkdir -p images_compressed

      - name: Copy images
        run: cp -r images/* images_compressed/

      - name: Commit copied images
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images_compressed/
          git commit -m "Copy images to images_compressed [CI skip]" || echo "No changes"
          git push
