name: Convert And Compress Images 

on:
  push:
    paths:
      - 'images/**'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./convert_and_compress.sh

      - name: Run conversion and compression script
        run: ./convert_and_compress.sh

      - name: Commit copied images
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add converted_images/
          git commit -m "convert and compress images [ci skip]" || echo "No changes"
          git push
